apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
description: Python Flask multi-stage deployment pipeline using Cloud Run
serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]
      strategy:
        standard:
          verify: false
    - targetId: stg
      profiles: ["staging"]
      strategy:
        standard:
          verify: false
    - targetId: prd
      profiles: ["production"]
      strategy:
        standard:
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Development environment in Cloud Run
run:
  region: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stg
description: Staging environment in Cloud Run
run:
  region: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prd
description: Production environment in Cloud Run
run:
  region: us-central1
