apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        standard:
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
