steps:
  # Terraform steps remain unchanged
  - name: "hashicorp/terraform:latest"
    entrypoint: "terraform"
    args: ["init"]
    dir: "terraform"
  - name: "hashicorp/terraform:latest"
    entrypoint: "terraform"
    args: ["apply", "-auto-approve"]
    dir: "terraform"

  # Build and push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:${_BUILD_ID}",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:${_BUILD_ID}",
      ]

  # Apply Cloud Deploy pipeline
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["deploy", "apply", "--file=clouddeploy.yaml", "--region=us-central1"]

  # Create release
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "deploy", "releases", "create",
        "release-${_BUILD_ID}",
        "--delivery-pipeline=flask-pipeline",
        "--region=us-central1",
        "--images=IMAGE=us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:${_BUILD_ID}",
        "--skaffold-file=skaffold.yaml"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _BUILD_ID: $BUILD_ID