apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
description: Python Flask multi-stage deployment pipeline using Cloud Run
serialPipeline:
  stages:
    - targetId: python-web-flask-dev
      profiles: ["dev"]
      strategy:
        standard:
          verify: false
    - targetId: python-web-flask-stg
      profiles: ["staging"]
      strategy:
        standard:
          verify: false
    - targetId: python-web-flask-prd
      profiles: ["production"]
      strategy:
        standard:
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: python-web-flask-dev
description: Development environment in Cloud Run
run:
  location: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: python-web-flask-stg
description: Staging environment in Cloud Run
run:
  location: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: python-web-flask-prd
description: Production environment in Cloud Run
run:
  location: us-central1
