apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]
      strategy:
        standard:
          postdeploy:
            actions: ["promote-to-stg"]  # Auto-promote after dev
    - targetId: stg
      profiles: ["stg"]
      strategy:
        standard:
          postdeploy:
            actions: ["promote-to-prd"]  # Auto-promote after staging
    - targetId: prd
      profiles: ["prd"]
      strategy:
        standard:
          postdeploy:
            actions: ["approve"]  # Manual approval for production
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: "Development Cloud Run service"
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stg
description: "Staging Cloud Run service"
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prd
description: "Production Cloud Run service"
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1