apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]
    - targetId: stg
      profiles: ["stg"]
    - targetId: prd
      profiles: ["prd"]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stg
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prd
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
requireApproval: true  # CORRECT placement for approval