apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: python-web-flask-pipeline
description: Python Flask multi-stage deployment pipeline using Cloud Run
serialPipeline:
  stages:
    - targetId: python-web-flask-pipeline-dev-target
      profiles: ["dev"]
      strategy:
        standard:
          verify: false
    - targetId: python-web-flask-pipeline-staging-target
      profiles: ["staging"]
      strategy:
        standard:
          verify: false
    - targetId: python-web-flask-pipeline-prod-target
      profiles: ["production"]
      strategy:
        standard:
          predeploy:
            actions:
              - name: manual-approval
                approvalRequired: true
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Development environment in Cloud Run
run:
  location: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging environment in Cloud Run
run:
  location: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production environment in Cloud Run
run:
  location: us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Service
metadata:
  name: python-web-flask-dev
  targetId: dev
spec:
  serviceYaml: service-dev.yaml
---
apiVersion: deploy.cloud.google.com/v1
kind: Service
metadata:
  name: python-web-flask-stg
  targetId: staging
spec:
  serviceYaml: service-stg.yaml
---
apiVersion: deploy.cloud.google.com/v1
kind: Service
metadata:
  name: python-web-flask-prd
  targetId: production
spec:
  serviceYaml: service-prd.yaml
