steps:
  # 1. Terraform Init
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['init']
    dir: 'terraform'

  # 2. Terraform Apply
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']
    dir: 'terraform'

  # 3. Build Docker image with tags for all environments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:${_BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-stg/stg:${_BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-stg/stg:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-prd/prd:${_BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-prd/prd:latest'
      - '.'

  # 4. Push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:${_BUILD_ID}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-stg/stg:${_BUILD_ID}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-stg/stg:latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-prd/prd:${_BUILD_ID}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-prd/prd:latest'

  # 5. Cloud Deploy apply
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy', 'apply',
        '--file=clouddeploy.yaml',
        '--region=us-central1'
      ]

 # 6. Create dev release with dev manifest
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create',
        'release-dev-${_BUILD_ID}',
        '--delivery-pipeline=flask-pipeline',
        '--region=us-central1',
        '--from-run-manifest=cloudrun-dev.yaml',
        '--description= standard promotion'
      ]
  # 7.  Promote to stg
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'promote',
        '--release=release-dev-${_BUILD_ID}',
        '--to-target=stg',
        '--region=us-central1'
      ]
    
   # 8.  Promote to Prd
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'promote',
        '--release=release-dev-${_BUILD_ID}',
        '--to-target=prd',
        '--region=us-central1'
      ]



    
 

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_ID: $BUILD_ID