apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        standard:
          verify: false
    - targetId: stg
      strategy:
        standard:
          verify: false
    - targetId: prd
      strategy:
        standard:
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
run:
  location: projects/YOUR_PROJECT_ID/locations/us-central1
  service: python-web-flask-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stg
run:
  location: projects/YOUR_PROJECT_ID/locations/us-central1
  service: python-web-flask-stg
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prd
run:
  location: projects/YOUR_PROJECT_ID/locations/us-central1
  service: python-web-flask-prd
