apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
description: "Cloud Run deployment pipeline with production approval"
serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]
      strategy:
        standard: {}
    - targetId: stg
      profiles: ["stg"]
      strategy:
        standard: {}
    - targetId: prd
      profiles: ["prd"]
      strategy:
        standard:
          # Correct approval configuration for Cloud Run
          postdeploy:
            actions: ["approve"]  # This creates the approval gate
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: "Development Cloud Run service"
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stg
description: "Staging Cloud Run service"
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prd
description: "Production Cloud Run service"
run:
  location: projects/silent-octagon-460701-a0/locations/us-central1