apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-web-flask-stg
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "cloud-deploy"
        deploy.cloud.google.com/target: "stg"
    spec:
      containers:
        - image: stg
      serviceAccountName: shopshere-product-service@silent-octagon-460701-a0.iam.gserviceaccount.com
      ports:
        - containerPort: 8080
      env:
        - name: ENV
          value: "stg"
  traffic:
    - latestRevision: true
      percent: 100
