apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-web-flask-dev
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "cloud-deploy"
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/python-web-flask-dev:$BUILD_ID
      serviceAccountName: shopshere-product-service@silent-octagon-460701-a0.iam.gserviceaccount.com
      ports:
        - containerPort: 8080
      env:
        - name: ENV
          value: "dev"
  traffic:
    - latestRevision: true
      percent: 100
