apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: python-web-flask
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  cloudrun:
    region: us-central1
    serviceName: python-web-flask-dev
    manifest:
      rawYaml:
        - service-dev.yaml

profiles:
  - name: stg
    deploy:
      cloudrun:
        region: us-central1
        serviceName: python-web-flask-stg
        manifest:
          rawYaml:
            - service-stg.yaml
  - name: prd
    deploy:
      cloudrun:
        region: us-central1
        serviceName: python-web-flask-prd
        manifest:
          rawYaml:
            - service-prd.yaml
