apiVersion: skaffold/v4beta9
kind: Config
profiles:
- name: dev
  manifests:
    rawYaml:
      - cloudrun/dev.yaml
      
- name: stg
  manifests:
    rawYaml:
      - cloudrun/stg.yaml
      
- name: prd
  manifests:
    rawYaml:
      - cloudrun/prd.yaml