apiVersion: skaffold/v4beta9
kind: Config
profiles:
- name: dev
  deploy:
    cloudrun: {}  # Explicit Cloud Run deployment
  manifests:
    rawYaml:
      - cloudrun/dev.yaml
      
- name: stg
  deploy:
    cloudrun: {}
  manifests:
    rawYaml:
      - cloudrun/stg.yaml
      
- name: prd
  deploy:
    cloudrun: {}
  manifests:
    rawYaml:
      - cloudrun/prd.yaml

customActions:
- name: approve
  containers:
  - name: approve-container  # Unique name
    image: gcr.io/cloud-builders/gcloud
    command: ["echo"]
    args: ["Approval placeholder"]

- name: promote-to-stg
  containers:
  - name: promote-stg-container  # Unique name
    image: gcr.io/cloud-builders/gcloud
    command: ["echo"]
    args: ["Auto-promoting to staging"]

- name: promote-to-prd
  containers:
  - name: promote-prd-container  # Unique name
    image: gcr.io/cloud-builders/gcloud
    command: ["echo"]
    args: ["Auto-promoting to production"]