apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-web-flask-stg
  namespace: default
  annotations:
    run.googleapis.com/client-name: "stg-deploy"
    run.googleapis.com/ingress: "all"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/revision-suffix: "${CD_RELEASE_UID}-stg"
    spec:
      containers:
        - image: "us-central1-docker.pkg.dev/silent-octagon-460701-a0/project4-dev/dev:latest"
          env:
            - name: ENV
              value: "stg"
      serviceAccountName: shopshere-product-service@silent-octagon-460701-a0.iam.gserviceaccount.com
      ports:
        - containerPort: 8080
  traffic:
    - latestRevision: true
      percent: 100